osx_image: xcode7.3
language: objective-c
cache:
  - bundler
  - cocoapods
before_install:
  - bundle install
  - pod repo update
install: bundle exec pod install
xcode_workspace: org.onebusaway.iphone.xcworkspace
xcode_scheme:
    - Debug
xcode_sdk:
    - iphonesimulator
script:
  - set -o pipefail && xcodebuild -workspace org.onebusaway.iphone.xcworkspace -scheme OneBusAway -sdk iphonesimulator -configuration Debug test ONLY_ACTIVE_ARCH=NO | xcpretty
notifications:
  slack:
    rooms:
      - onebusaway:kcIbPpOOuJEhNgpzWMd8gkqj
    on_success: change
    on_failure: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/30e6e2d8791d3099cbe5
    on_success: always
    on_failure: always
    on_start: true
